abstractive:
  default_to_run:
  - bart
  - t5
  - flan_t5_base
  generation:
    max_length: 150
    min_length: 50
extractive:
  algorithms:
  - tfidf
  - sumy_textrank
  - sumy_lexrank
gemini:
  api_key: AIzaSyAYS0rW34espxdWbwJRdS1mTDaJ41GWjuw
  enabled: true
  style: Standard
output:
  excel_filename: full_summarization_report.xlsx
paths:
  input_path: C:\Users\Bala Sankar\Downloads\acc_new_sum\AI-Repo\temp_uploads\Global
    warming refers to the increase in the planet.docx
  output_text: C:\Users\Bala Sankar\Downloads\acc_new_sum\AI-Repo\temp_uploads\converted.txt
processing:
  use_gpu: false
